version: '3'
volumes:
  pgdata:
services:
  python:
    # image: python:3.4
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
  postgres:
    image: postgres:10.3
    environment:
      POSTGRES_USER: tickets
      POSTGRES_DB: tickets
      POSTGRES_PASS: tickets
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
